global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Cargar reglas de alerting y SLO
rule_files:
  - '/etc/prometheus/alert-rules.yml'
  - '/etc/prometheus/slo-rules.yml'

scrape_configs:
  # Prometheus se auto-monitorea
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'users-api'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'products-service'
    static_configs:
      - targets: ['products-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'orders-service'
    static_configs:
      - targets: ['orders-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'payments-service'
    static_configs:
      - targets: ['payments-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 10s
